require 'yaml'
settings = YAML.load_file 'localvars.yml'

Vagrant.configure("2") do |config|

  # Write an ansible inventory file based on what we know about our ssh ports
  # We could also do this dynamically by parsing the output from vagrant ssh-config
  inventory = ''
  settings['SSH_PORTS'].each do | key, value |
    # These paths are relative to the VM file system, i.e. they are pointing to 
    # the automatically created /vagrant synced directory.  On the host that should 
    # be where this Vagrantfile is
    if settings['REPLACE_INSECURE_KEY'] then
      sshkeypath = "/vagrant/.vagrant/machines/#{key}/virtualbox/private_key"
    else
      sshkeypath = "/vagrant/insecure_private_key"
    end

    # If you're using preexisting ansible control machine, add vbhost to your /etc/hosts file manually.
    # Otherwise vbhost will be added to the ansible control machine hosts file by the ansible.sh provisioning script,
    # vbhost should point to the virtualbox host machine. From there we port forward to ssh on each virtualbox guest
    inventory += "#{key} ansible_host=vbhost ansible_port=#{value} ansible_user='vagrant' ansible_ssh_private_key_file='#{sshkeypath}'\n"
  end
  File.open('ansible_hosts','w') do |h| 
   h.write inventory
  end


  # Settings common to all VMs
  config.vm.box = "ubuntu/xenial64"
  config.ssh.insert_key = settings['REPLACE_INSECURE_KEY']
  config.vm.provision :shell, path: "python-ubuntu.sh"
  
  # On windows hosts the vagrant shared folder comes up as having 777 i.e. wide open
  # and because the private key is there, ssh does NOT approve
  # See https://stackoverflow.com/questions/29021246/ssh-fails-due-to-key-file-permissions-when-i-try-to-provision-a-vagrant-vm-with?rq=1
  config.vm.synced_folder "./", "/vagrant", 
     owner: "vagrant",
     mount_options: ["dmode=775,fmode=600"]

  # Per machine settings - jersey
  config.vm.define "readify-jersey" do |jersey|

    machine_name = "readify-jersey"

    jersey.vm.hostname = machine_name
    jersey.vm.network "forwarded_port", guest: 8080, host: settings['HTTP_PORTS'][machine_name]
    jersey.vm.network "forwarded_port", guest: 22, host: settings['SSH_PORTS'][machine_name], id: "ssh"

    jersey.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end

  end

  # provision an ansible control machine if desired (necessary if the host is windows)
  if settings['PROVISION_ANSIBLE_CONTROL'] then

    # Per machine settings - ansible
    config.vm.define "ansible" do |ansible|

      machine_name = "ansible"

      ansible.vm.hostname = machine_name
      ansible.vm.network "forwarded_port", guest: 22, host: settings['SSH_PORTS'][machine_name], id: "ssh"
      ansible.vm.synced_folder "../ansible", "/ansible"

      ansible.vm.provider "virtualbox" do |vb|
        vb.memory = 512
      end

      ansible.vm.provision :shell, path: "ansible.sh"
    end

  end


end
