require 'yaml'
settings = YAML.load_file 'localvars.yml'

Vagrant.configure("2") do |config|


  # Common settings
  config.vm.box = "ubuntu/xenial64"

  # On windows hosts the vagrant shared folder comes up as having 777 i.e. wide open
  # and because the private key is there, ssh does NOT approve
  # See https://stackoverflow.com/questions/29021246/ssh-fails-due-to-key-file-permissions-when-i-try-to-provision-a-vagrant-vm-with?rq=1
  config.vm.synced_folder "./", "/vagrant", 
     owner: "vagrant",
     mount_options: ["dmode=775,fmode=600"]

  # Per machine settings
  config.vm.define "readify-jersey" do |jersey|

    machine_name = "readify-jersey"

    jersey.vm.hostname = machine_name
    jersey.vm.network "forwarded_port", guest: 80, host: settings.HTTP_PORTS[machine_name]
    jersey.vm.network "forwarded_port", guest: 22, host: settings.SSH_PORTS[machine_name], id: "ssh"

    jersey.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end
  end

  # provision an ansible control machine if the host is windows
  if settings.PROVISION_ANSIBLE_CONTROL then

    # Per machine settings
    config.vm.define "ansible" do |ansible|

      machine_name = "ansible"

      ansible.vm.hostname = machine_name
      ansible.vm.network "forwarded_port", guest: 22, host: settings.SSH_PORTS[machine_name], id: "ssh"
      ansible.vm.synced_folder "../ansible", "/ansible"

      ansible.vm.provider "virtualbox" do |vb|
        vb.memory = 512
      end

      ansible.vm.provision :shell, path: "ansible.sh"
    end

  end


end

