- name: install samba codeclient
  apt: pkg={{item}} state=installed
  become: true
  with_items:
   - cifs-utils 
   - samba-common
   - samba 

- name: add connection script
  template: src=connect.sh dest=/home/vagrant/connect.sh

- name: make connection script executable
  file: 
    path: /home/vagrant/connect.sh
    mode: +x

- name: invoke connection script
  command: /home/vagrant/connect.sh
  become: true