Vagrant.configure("2") do |config|

  machine_name = "readify-jersey"

  config.vm.hostname = machine_name
  config.vm.network "forwarded_port", guest: 80, host: HTTP_PORTS[machine_name]

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "../../ansible/playbook.yml"
  end



end